[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200      ; Serial Monitor speed
monitor_echo = yes          ; Echo input back to Serial Monitor

lib_deps =
    madhephaestus/ESP32Servo @ ^0.13.0
    madhephaestus/ESP32Servo